SOVIET_REPOS=https://raw.githubusercontent.com/Soviet-Linux/OUR/main
SOVIET_FORMATS=ecmp
CARCH=x86_64
CHOST=x86_64-pc-linux-gnu
CFLAGS=-march=x86-64-v2 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection
CXXFLAGS=-march=x86-64-v2 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
LTOFLAGS=-flto=auto
MAKEFLAGS=-j1
NINJAJOBS=1
